### ISSUE TITLE
Kafka metrics missing when the unit is under load.

### ISSUE THREAD

**Issue by peterctl** [canonical/kafka-operator#146]
## Summary
Under load, the Kafka metrics exporter will take a very long time to return metrics (we saw times above 45 seconds), but the grafana agent in the machine will time out the request after just 10 seconds. When this happens, Prometheus stops receiving metrics from Kafka and the “Kafka Missing” alert fires. I can think of 2 possible solutions to this issue:
- Configure a larger timeout on the grafana agent for the Kafka exporter.
- Change the niceness of the exporter process to give it a higher priority so that it will return the metrics on time even when Kafka is overloaded. This might require switching the jmx_exporter with kafka_exporter as I don't know if process niceness can be changed for a single thread. Perhaps it could be tweaked at the JVM level?

## Steps to reproduce
1. Overload the Kafka cluster so that CPU load is above 1 per CPU core.

## Expected behavior
Metrics would still show up. The `up` metric should remain at 1.

## Actual behavior
Metrics disappear altogether and the "Kafka Missing" alert fires. The `up` metric goes to 0 even though Kafka is up.

Images for expected and actual behavior can be seen [in this private MM message](https://chat.canonical.com/canonical/pl/34i5h7pk1jnhmxi1j5pbbnbona).

## Versions

Operating system: Ubuntu 22.04.2 LTS (jammy)
Juju CLI: 2.9.45-ubuntu-amd64
Juju agent: 2.9.42
Charm revision: 121
LXD: N/A (No LXD containers running in this model)

## Additional context
Private MM thread where I dug into the issue and found the root cause:
https://chat.canonical.com/canonical/pl/u5e8m6j8itrcxqqizpfehxu78a

**Comment by marcoppenheimer** [comment]
Thanks for raising this!

So generally JMX is fairly slow under normal circumstances, so >= 10s exports aren't unheard of.
I'm not sure we want to go down the rabbit hole of configuring JMX exporter niceness, so it might be worth raising the issue on the https://github.com/canonical/grafana-agent-k8s-operator to get some insight there one what can be done with the timeouts?

Specifically these docs - https://grafana.com/docs/agent/latest/static/configuration/metrics-config/#global_config

**Comment by przemeklal** [comment]
@marcoppenheimer I ran into the same issue and managed to temporarily work it around by setting scrape_timeout to 1m:
```
metrics:
  global:
    scrape_timeout: 1m
```
 in this part of the config (`/etc/grafana-agent.yaml`):
```
...
metrics:
  global:
    scrape_timeout: 1m
  configs:
  - name: agent_scraper
    remote_write:
    - tls_config:
        insecure_skip_verify: false
      url: http://<redacted>:80/cos-prometheus-0/api/v1/write
    scrape_configs:
    - job_name: kafka_0
      metrics_path: /metrics
      static_configs:
      - labels:
          instance: <redacted>_kafka/1
          juju_application: kafka
          juju_model: preprod-kafka
          juju_model_uuid: <redacted>
          juju_unit: kafka/1
        targets:
        - localhost:9101
  wal_directory: /tmp/agent/data
```

I created https://github.com/canonical/grafana-agent-operator/issues/14 to determine what can be done about this issue.
