### ISSUE TITLE
Digicert does not allow '/' in CN or SANs ; charm creates CSRs with SAN "kafka/{unit-nb}" which is not copied to signed cert by Digicert

### ISSUE THREAD

**Issue by Thinking-Dragon** [canonical/kafka-operator#290]
## ℹ️ TL ; DR
You can skip to **Explanation** and **Solution** down below if you want to go straight to what is happening.

## Steps to reproduce

1. To reproduce this bug, you will need a Digicert account with a Certificate Authority set up to sign CSRs.
2. Create `kafka.yaml`
```yaml
applications:
  kafka:
    channel: 3/stable
    charm: kafka
    num_units: 3
    base: ubuntu@22.04
  manual-tls-certificates:
    charm: manual-tls-certificates
    channel: latest/stable
    num_units: 1
  external-ca:
    channel: latest/stable
    charm: tls-certificates-operator
    num_units: 1
    base: ubuntu@22.04
    options:
      generate-self-signed-certificates: True
  zookeeper:
    channel: 3/stable
    charm: zookeeper
    num_units: 3
    base: ubuntu@22.04
  data-integrator:
    channel: latest/stable
    charm: data-integrator
    num_units: 1
    base: ubuntu@22.04
    options:
      topic-name: "default"
      extra-user-roles: "admin"

base: ubuntu@22.04

relations:
- - zookeeper:certificates
  - manual-tls-certificates:certificates
- - kafka:certificates
  - manual-tls-certificates:certificates
- - kafka:zookeeper
  - zookeeper:zookeeper
- - kafka
  - data-integrator
- - external-ca:certificates
  - kafka:trusted-ca
```
3. Run `juju deploy ./kafka.yaml` and wait for the deployment to settle down. You should see six outstanding CSRs when you run `juju status`.
4. Run the following script to extract CSRs from the `manual-tls-certificates` charm:
> ⚠️ The following scripts expect the `~/deployment` directory to exist, run `mkdir ~/deployment` or modify the scripts to point to another directory before running the scripts.
```bash
#!/bin/bash

if [[ "$#" -ne 1 ]]; then
  echo "Usage: extract-csrs.sh <deployment-juju-model>"
  exit 1
fi

deployment="$1"

mkdir -p ~/deployment/csrs/$deployment/to-sign
mkdir -p ~/deployment/csrs/$deployment/signed

csrs_json=$(juju run manual-tls-certificates/0 get-outstanding-certificate-requests --format=json | jq -r '.["manual-tls-certificates/0"].results.result')
echo "${csrs_json//\'/\"}" > ~/deployment/csrs/$deployment/csrs.json

for i in $(seq 0 $(jq 'length - 1' ~/deployment/csrs/$deployment/csrs.json));
do
  unit=$(jq -r ".[$i].unit_name" ~/deployment/csrs/$deployment/csrs.json | sed 's|/|_|g')
  yq -r ".[$i].csr" ~/deployment/csrs/$deployment/csrs.json > ~/deployment/csrs/$deployment/to-sign/$unit.csr
done
```
5. You will find the CSRs under `~/deployment/csrs/{your-model-name}/to-sign`, sign the CSRs using Digicert and place the signed certificates under `~/deployment/csrs/{your-model-name}/signed`. Make sure you name the signed certificates with the same format as the CSRs but with the `.pem` extension. If the CSRs are `kafka_0.csr`, `kafka_1.csr`, etc. then your signed certificates must be `kafka_0.pem`, `kafka_1.pem`.
6. Run the following script to provide the signed certificates back to Kafka and ZooKeeper
> ⚠️ You will need to adapt to script to point to your ca-chain files on your computer (replace the `[...]` sections)
```bash
#!/bin/bash

if [[ "$#" -ne 1 ]]; then
  echo "Usage: provide-signed-certificates.sh <deployment-juju-model>"
  exit 1
fi

deployment="$1"
tls_unit="0"

for i in $(seq 0 $(jq 'length - 1' ~/deployment/csrs/$deployment/csrs.json));
do
  unit=$(jq -r ".[$i].unit_name" ~/deployment/csrs/$deployment/csrs.json | sed 's|/|_|g')
  relation_id=$(jq -r ".[$i].relation_id" ~/deployment/csrs/$deployment/csrs.json)

  juju run -m $deployment manual-tls-certificates/$tls_unit provide-certificate \
    certificate-signing-request="$(base64 -w0 ~/deployment/csrs/$deployment/to-sign/$unit.csr)" \
    certificate="$(base64 -w0 ~/deployment/csrs/$deployment/signed/$unit.pem)" \
    ca-certificate="$(base64 -w0 [...]/ca-chain-ri.pem)"
done
```
7. Wait for the deployment to settle.

## Expected behavior
When I run `juju status`, I should see all nodes `active` and the `manual-tls-certificates` application should say `No outstanding requests.`.

## Actual behavior

When I run `juju status`, I see the ZooKeeper nodes are active, but the `manual-tls-certificates` application says that there are three outstanding requests (these are three new requests). If I sign these three, the Kafka charm generates three more.

## Explanation
The reason for this behavior is that the CSRs generated by the Kafka charm have the following two SANs:
1. `hostname` of the unit's machine
2. `kafka/{unit-nb}`

From [digicert.com](https://www.digicert.com/kb/ssl-support/underscores-not-allowed-in-fqdns.htm):
>  We can only issue certificates for domains and subdomains using:
>      Lowercase letters a–z
>      Uppercase letters A–Z
>      Digits 0–9
>      Special characters: period (.) and hyphen (‐)

As you can see `/` is not one of the allowed characters. When you sign the CSRs with Digicert, the `kafka/{unit-nb}` SAN will be ignored and not copied over to the signed certificate.

This makes the charm think it has changed domain and it regenerates CSRs to be signed again.

## Solution
There could be a new configuration option added to the charm to specify an alternative name for these SANs so that we can format them in a way that pleases Digicert when we deploy for clients who use Digicert.

## Versions

Operating system: Ubuntu 22.04.5 LTS

Juju CLI: 3.5.4-genericlinux-amd64

Juju agent: 3.5.4

Charm revision: 149

LXD: 5.0.3
