### ISSUE TITLE
hook failed: "certificates-relation-changed" on Openstack - charmed-kafka.keytool: not found

### ISSUE THREAD

**Issue by asbalderson** [canonical/kafka-operator#329]
## Steps to reproduce

1.  we the bundle below on openstack, 1 of the 3 kafka units failed to come up with a certificates-relation-changed hook failure, and the error appears to be because charmed-kafka.keytool was not found on that unit.
```
applications:
  kafka:
    bindings:
      ? ''
      : alpha
    channel: 3/stable
    charm: kafka
    constraints: mem=8G root-disk=11G
    num_units: 3
    series: jammy
  ntp:
    bindings:
      ? ''
      : alpha
    charm: ntp
    options:
      source: ntp.ubuntu.com
      verify_ntp_servers: true
  self-signed-certificates:
    bindings:
      ? ''
      : alpha
    channel: latest/stable
    charm: self-signed-certificates
    num_units: 1
    series: jammy
  zookeeper:
    bindings:
      ? ''
      : alpha
    charm: zookeeper
    constraints: root-disk=11G
    num_units: 3
    series: jammy
series: jammy
relations:
- ['kafka:certificates', 'self-signed-certificates:certificates']
- ['kafka:juju-info', 'ntp:juju-info']
- ['kafka:zookeeper', 'zookeeper:zookeeper']
- ['ntp:juju-info', 'self-signed-certificates:juju-info']
- ['ntp:juju-info', 'zookeeper:juju-info']
- ['self-signed-certificates:certificates', 'zookeeper:certificates']
```

## Versions
Kafka 3/stable  rev 195 on Jammy
self-signed-certificates  latest/stable rev  264 Jammy
zookeeper  3/stable  rev 149  on Jammy

version: 3.6.4
rev: 30244
channel/risk: 3/stable

Juju agent: 3.6.4

Charm revision: are above

## Log output

When we deploy on openstack, we deploy on a private network and cant directly view the logs, but we do get logs from the controller
the logsync shows the following information:
```
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:39 DEBUG unit.kafka/2.juju-log server.go:326 certificates:7: Emitting Juju event certificates_relation_changed. 
0/baremetal/var/log/juju/logsink.log:d62f51f1-1dd2-4cfd-89a9-29c28c30a58e: machine-0 2025-04-12 00:19:39 DEBUG juju.apiserver request_notifier.go:189 <- [4D] unit-kafka-2 {"request-id":1074,"type":"Uniter","version":20,"request":"
ReadRemoteSettings","params":"'params redacted'"} 
0/baremetal/var/log/juju/logsink.log:d62f51f1-1dd2-4cfd-89a9-29c28c30a58e: machine-0 2025-04-12 00:19:39 DEBUG juju.apiserver request_notifier.go:221 -> [4D] unit-kafka-2 2.387744ms {"request-id":1074,"response":"'body redacted'"}
 Uniter[""].ReadRemoteSettings 
0/baremetal/var/log/juju/logsink.log:d62f51f1-1dd2-4cfd-89a9-29c28c30a58e: machine-0 2025-04-12 00:19:39 DEBUG juju.apiserver request_notifier.go:189 <- [4D] unit-kafka-2 {"request-id":1075,"type":"Uniter","version":20,"request":"ReadSettings","params":"'params redacted'"} 
0/baremetal/var/log/juju/logsink.log:d62f51f1-1dd2-4cfd-89a9-29c28c30a58e: machine-0 2025-04-12 00:19:39 DEBUG juju.apiserver request_notifier.go:221 -> [4D] unit-kafka-2 2.014853ms {"request-id":1075,"response":"'body redacted'"} Uniter[""].ReadSettings 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:39 DEBUG unit.kafka/2.juju-log server.go:326 certificates:7: Emitting custom event <CertificateAvailableEvent via KafkaCharm/TLSCertificatesRequiresV1[certificates]/on/certificate_available[87]>. 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:39 DEBUG unit.kafka/2.juju-log server.go:326 certificates:7: Non-existing field 'ca' was attempted to be removed from the databag (relation ID: 0) 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:39 DEBUG unit.kafka/2.juju-log server.go:326 certificates:7: output='' 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:39 DEBUG unit.kafka/2.juju-log server.go:326 certificates:7: output='' 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:39 DEBUG unit.kafka/2.juju-log server.go:326 certificates:7: output='' 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:39 DEBUG unit.kafka/2.juju-log server.go:326 certificates:7: cmd failed - cmd=charmed-kafka.keytool -import -v -alias ca -file ca.pem -keystore truststore.jks -storepass l7Qvg1oPnVEVvKamF8YyzTWgeeHUc1t8 -noprompt, stdout=, stderr=/bin/sh: 1: charmed-kafka.keytool: not found
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:39 ERROR unit.kafka/2.juju-log server.go:326 certificates:7: Uncaught exception while in charm code:
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/./src/charm.py", line 432, in <module>
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/main.py", line 555, in __call__
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/main.py", line 544, in main
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/main.py", line 520, in run
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/main.py", line 509, in _emit
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/main.py", line 143, in _emit_charm_event
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/framework.py", line 350, in emit
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/framework.py", line 849, in _emit
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/framework.py", line 939, in _reemit
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/lib/charms/tls_certificates_interface/v1/tls_certificates.py", line 1309, in _on_relation_changed
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/framework.py", line 350, in emit
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/framework.py", line 849, in _emit
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/venv/ops/framework.py", line 939, in _reemit
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/src/events/tls.py", line 268, in _on_certificate_available
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/src/managers/tls.py", line 89, in set_truststore
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/src/managers/tls.py", line 81, in set_truststore
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/src/workload.py", line 89, in exec
0/baremetal/var/log/juju/logsink.log:  File "/var/lib/juju/agents/unit-kafka-2/charm/src/workload.py", line 77, in exec
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:40 ERROR juju.worker.uniter.operation runhook.go:180 hook "certificates-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:40 DEBUG juju.machinelock machinelock.go:206 created rotating log file "/var/log/juju/machine-lock.log" with max size 10 MB and max backups 5 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:40 DEBUG juju.machinelock machinelock.go:190 machine lock "machine-lock" released for kafka/2 uniter (run relation-changed (7; unit: self-signed-certificates/0) hook) 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:40 DEBUG juju.worker.uniter.operation executor.go:118 lock released for kafka/2 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:40 DEBUG juju.worker.uniter.actions resolver.go:87 no next action from pending=[]; completed=map[] 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:40 INFO juju.worker.uniter resolver.go:180 awaiting error resolution for "relation-changed" hook 
0/baremetal/var/log/juju/logsink.log:735700ab-d235-4613-82cf-d12c78ee6996: unit-kafka-2 2025-04-12 00:19:40 DEBUG juju.worker.uniter agent.go:22 [AGENT-STATUS] error: hook failed: "certificates-relation-changed" 

```
